import React,{useMemo,useState} from 'react'
import { NavLink,useParams } from 'react-router-dom'
import { docs,docGroups } from '../docsContentV1.js'
import { Code } from '../components.jsx'
import { ArticleProgress,Reveal } from '../motion/primitives.jsx'

function DocsMenu({query,setQuery}){const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return docs;return docs.filter(d=>`${d.title} ${d.summary} ${d.group}`.toLowerCase().includes(q))},[query]);return <aside className="docs-menu"><div className="docs-menu-head"><span>MANUAL / 1.0</span><b>{docs.length} TOPICS</b></div><label className="docs-search"><span>SEARCH</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="HTTP, .nqd, safety…"/></label>{docGroups.map(group=>{const items=visible.filter(d=>d.group===group);return items.length?<div className="docs-group" key={group}><h4>{group}</h4>{items.map(d=><NavLink key={d.slug} to={`/docs/${d.slug}`}>{d.title}</NavLink>)}</div>:null})}</aside>}
function DocsIndex(){return <article className="docs-article docs-index"><Reveal className="doc-kicker" distance={6}>NOQERI 1.0 DOCUMENTATION</Reveal><Reveal as="h1" delay={.035} distance={18}>One manual from first program to web + data.</Reveal><Reveal as="p" className="doc-lead" delay={.07} distance={10}>The manual treats features as contracts, including their current limits. Start with ordinary language syntax, then move into systems, `.nqo` web objects, HTTP hosting, `.nqd` data and the package/security model.</Reveal><div className="docs-start-grid">{docs.slice(0,10).map((d,i)=><NavLink key={d.slug} to={`/docs/${d.slug}`}><small>{String(i+1).padStart(2,'0')}</small><strong>{d.title}</strong><span>{d.summary}</span></NavLink>)}</div><section className="doc-section"><h2>Documentation rule</h2><p>A package declaration, roadmap name or host contract is not documented as “working” unless the implementation path exists. Experimental providers are labelled as such; the manual does not inflate maturity ratings.</p></section></article>}
function DocArticle({doc}){const index=docs.findIndex(d=>d.slug===doc.slug),prev=docs[index-1],next=docs[index+1];return <ArticleProgress className="docs-progress-scope"><article className="docs-article"><Reveal className="doc-kicker" distance={6}>{doc.group} / {String(index+1).padStart(2,'0')}</Reveal><Reveal as="h1" delay={.035} distance={18}>{doc.title}</Reveal><Reveal as="p" className="doc-lead" delay={.07} distance={10}>{doc.summary}</Reveal>{doc.sections.map((section,i)=><Reveal as="section" className="doc-section" key={i} amount={.12} distance={8}><h2>{section.title}</h2>{section.paragraphs.map((p,j)=><p key={j}>{p}</p>)}{section.points?.length>0&&<ul>{section.points.map(x=><li key={x}>{x}</li>)}</ul>}</Reveal>)}{doc.code&&<Reveal distance={8}><Code label="NOQERI / EXAMPLE">{doc.code}</Code></Reveal>}{doc.note&&<div className="doc-note"><b>NOTE</b><span>{doc.note}</span></div>}<nav className="docs-prev-next">{prev?<NavLink className="doc-prev" to={`/docs/${prev.slug}`}><small>← PREVIOUS</small>{prev.title}</NavLink>:<span/>}{next?<NavLink className="doc-next" to={`/docs/${next.slug}`}><small>NEXT →</small>{next.title}</NavLink>:<span/>}</nav></article></ArticleProgress>}
export function Docs(){const params=useParams(),slug=params['*']?.replace(/^\//,'')||'';const[query,setQuery]=useState('');const doc=docs.find(d=>d.slug===slug);return <div className="docs-layout"><DocsMenu query={query} setQuery={setQuery}/>{slug?(doc?<DocArticle doc={doc}/>:<article className="docs-article"><div className="doc-kicker">404 / DOCS</div><h1>Topic not found.</h1><p className="doc-lead">Use the manual index or sidebar search to continue.</p><NavLink className="cta" to="/docs">Documentation index →</NavLink></article>):<DocsIndex/>}</div>}
