import React,{useEffect,useMemo,useState} from 'react'
import {AnimatePresence,motion} from 'motion/react'
import {Page} from '../components.jsx'
import {useNoqeriMotion} from '../motion/MotionProvider.jsx'
const filters=['All','Core','Web','Data','Security','Tools','Platform']
function packageCommands(pkg,release){const origin=typeof window!=='undefined'?window.location.origin:'https://noqeri.onrender.com';const url=`${origin}/registry/${pkg.namespace}/${pkg.name}/${release.version}/download.nqpkg`,file=`${pkg.namespace}-${pkg.name}-${release.version}.nqpkg`;return{unix:`curl -fL "${url}" -o "${file}"`,powershell:`Invoke-WebRequest -Uri "${url}" -OutFile "${file}"`}}
function categoryFor(pkg){const hay=`${pkg.namespace} ${pkg.name} ${pkg.description||''} ${pkg.category||''}`.toLowerCase();if(/web|http|dom|browser/.test(hay))return'Web';if(/data|json|db|sql/.test(hay))return'Data';if(/crypto|security|hash|auth/.test(hay))return'Security';if(/tool|format|test|lsp/.test(hay))return'Tools';if(/platform|native|system|os/.test(hay))return'Platform';return'Core'}
function Command({label,value}){const[copied,setCopied]=useState(false);async function copy(){if(!navigator.clipboard)return;await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1300)}return <div className="package-command"><div><span>{label}</span><button type="button" onClick={copy}>{copied?'COPIED ✓':'COPY'}</button></div><code>{value}</code></div>}
function PackageRow({pkg,index}){const[open,setOpen]=useState(false),{reduced,tokens}=useNoqeriMotion(),release=pkg.versions?.[0];if(!release)return null;const commands=packageCommands(pkg,release),category=categoryFor(pkg);return <motion.article layout={!reduced} className={`package-row package-catalog-row${open?' is-open':''}`} transition={{layout:tokens.spring}}><div className="package-index">{String(index+1).padStart(2,'0')}</div><div className="package-identity"><small>{category} / {pkg.namespace}</small><h3>{pkg.name}</h3></div><p>{pkg.description}</p><div className="package-meta"><span>version {release.version}</span>{release.experimental&&<b>experimental</b>}<a href={`/registry/${pkg.namespace}/${pkg.name}/${release.version}/download.nqpkg`}>Download ↓</a><button className="package-install-toggle" type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Close':'install ↘'}</button></div><AnimatePresence initial={false}>{open&&<motion.div className="package-install-panel" initial={reduced?false:{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}><div className="package-command-grid"><Command label="LINUX / macOS" value={commands.unix}/><Command label="WINDOWS POWERSHELL" value={commands.powershell}/></div></motion.div>}</AnimatePresence></motion.article>}
export function Packages(){const[index,setIndex]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('All');useEffect(()=>{fetch('/registry/index.json').then(r=>{if(!r.ok)throw new Error('registry unavailable');return r.json()}).then(setIndex).catch(e=>setError(e.message))},[]);const packages=useMemo(()=>{const all=index?.packages||[],q=query.trim().toLowerCase();return all.filter(pkg=>(!q||`${pkg.namespace}/${pkg.name} ${pkg.description}`.toLowerCase().includes(q))&&(filter==='All'||categoryFor(pkg)===filter))},[index,query,filter]);return <Page kicker="PACKAGES / CATALOGUE" title="Packages that make the small language feel wide." intro="Noqeri packages should feel deterministic, inspectable and close to the language. Browse official surfaces for web, data, security, tooling and platform work."><div className="package-stat-strip"><span>{index?index.packages.length:'—'}</span><small>PUBLISHED PACKAGES</small></div><div className="package-toolbar"><label className="package-filter"><span className="sr-only">Search packages</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search packages, categories or commands"/></label><div className="package-chips">{filters.map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{error&&<div className="notice">{error}</div>}<motion.div layout className="package-list">{packages.map((pkg,i)=><PackageRow key={`${pkg.namespace}/${pkg.name}`} pkg={pkg} index={i}/>)}</motion.div>{index&&packages.length===0&&<div className="package-empty">Nothing matched. Clear filters and try another package name.</div>}</Page>}
