import { spawn } from 'node:child_process'
const port=18080
const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','inherit']})
const stop=()=>child.kill('SIGTERM')
process.on('exit',stop)
try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('server start timeout')),12000);child.stdout.on('data',data=>{if(String(data).includes('listening')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`server exited ${code}`)))})
  const health=await fetch(`http://127.0.0.1:${port}/api/health`).then(r=>r.json())
  if(health.status!=='ok'||health.source!=='Noqeri'||health.language!=='1.0')throw new Error('Noqeri API health mismatch')
  const meta=await fetch(`http://127.0.0.1:${port}/api/meta`).then(r=>r.json())
  if(meta.compiler!=='1.0.0')throw new Error('Noqeri API metadata mismatch')
  const db=await fetch(`http://127.0.0.1:${port}/api/db-demo`).then(r=>r.text())
  if(!db.includes('status')||!db.includes('ok'))throw new Error('NoqeriDB web-host integration failed')
  const registry=await fetch(`http://127.0.0.1:${port}/registry/index.json`).then(r=>r.json())
  if(!registry.packages?.some(p=>p.name==='json'))throw new Error('registry web index missing package')
  const archive=await fetch(`http://127.0.0.1:${port}/registry/noqeri/json/1.0.0/download.nqpkg`)
  if(!archive.ok)throw new Error('package web download failed')
  if(archive.headers.get('content-type')!=='application/vnd.noqeri.package+gzip')throw new Error('package web MIME mismatch')
  const bytes=await archive.arrayBuffer()
  if(bytes.byteLength===0)throw new Error('package web archive was empty')
  const docs=await fetch(`http://127.0.0.1:${port}/docs/http-server`)
  if(!docs.ok||(await docs.text()).indexOf('<div id="root"></div>')<0)throw new Error('SPA docs fallback failed')
  const home=await fetch(`http://127.0.0.1:${port}/`)
  if(!home.headers.get('content-security-policy'))throw new Error('security headers missing')
  console.log('web, Noqeri API, NoqeriDB and registry download smoke tests passed')
} finally {stop()}
