import React,{useEffect,useRef,useState} from 'react'
import {AnimatePresence,motion} from 'motion/react'
import {NavLink,Route,Routes,useLocation} from 'react-router-dom'
import {Home} from './pages/Home.jsx';import {Language} from './pages/Language.jsx';import {Docs} from './pages/Docs.jsx';import {Packages} from './pages/Packages.jsx';import {Registry} from './pages/Registry.jsx';import {Ecosystem} from './pages/Ecosystem.jsx';import {Benchmarks} from './pages/Benchmarks.jsx';import {Install} from './pages/Install.jsx';import {Playground} from './pages/Playground.jsx';import {Community} from './pages/Community.jsx';import {About} from './pages/About.jsx';import {NotFound} from './pages/NotFound.jsx'
import {clientVersion} from './noqeri/client.generated.nqo'
import {useNoqeriMotion} from './motion/MotionProvider.jsx'
import {InteractionRuntime} from './motion/InteractionRuntime.jsx'
const nav=[['Language','/language'],['Docs','/docs'],['Packages','/packages'],['Registry','/registry'],['Ecosystem','/ecosystem']]
function GithubIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .7a11.3 11.3 0 0 0-3.57 22c.57.1.78-.25.78-.55v-2.2c-3.18.7-3.85-1.35-3.85-1.35-.52-1.32-1.27-1.67-1.27-1.67-1.04-.71.08-.7.08-.7 1.15.08 1.75 1.18 1.75 1.18 1.02 1.75 2.68 1.25 3.34.96.1-.74.4-1.25.73-1.54-2.54-.29-5.21-1.27-5.21-5.59 0-1.23.44-2.24 1.17-3.03-.12-.29-.51-1.45.11-3 0 0 .95-.31 3.11 1.16A10.8 10.8 0 0 1 12 6.99c.96 0 1.93.13 2.84.38 2.16-1.47 3.11-1.16 3.11-1.16.62 1.55.23 2.71.11 3 .73.79 1.8 1.17 3.03 0 4.33-2.68 5.29-5.23 5.57.41.35.78 1.05.78 2.12v3.22c0 .3.21.66.79.55A11.3 11.3 0 0 0 12 .7Z"/></svg>}
function PageMeta(){const l=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});const p=l.pathname==='/'?'Noqeri':l.pathname.split('/').filter(Boolean).join(' · ');document.title=`${p.replace(/\b\w/g,c=>c.toUpperCase())} — Noqeri`},[l.pathname]);return null}
function CursorFollower(){const {reduced}=useNoqeriMotion();const ref=useRef(null);useEffect(()=>{if(reduced||!matchMedia('(hover:hover) and (pointer:fine)').matches)return;const el=ref.current;const move=e=>{el.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`};const over=e=>el.dataset.mode=e.target.closest('a,button,[data-cursor]')?.dataset.cursor|| (e.target.closest('a,button')?'action':'');window.addEventListener('pointermove',move);document.addEventListener('pointerover',over);return()=>{window.removeEventListener('pointermove',move);document.removeEventListener('pointerover',over)}},[reduced]);if(reduced)return null;return <div className="cursor-follower" ref={ref} aria-hidden="true"><span/></div>}
function SlashTransition({path}){const {reduced}=useNoqeriMotion();if(reduced)return null;return <motion.div key={path} className="slash-transition" initial={{scaleX:0,x:'-55%'}} animate={{scaleX:[0,1,1,0],x:['-55%','0%','0%','55%']}} transition={{duration:.5,times:[0,.38,.62,1],ease:[.22,1,.36,1]}} aria-hidden="true"/>}
export default function App(){const l=useLocation(),[compact,setCompact]=useState(false),{reduced,tokens}=useNoqeriMotion();useEffect(()=>{let last=scrollY;const fn=()=>{setCompact(scrollY>22&&scrollY>=last-4);last=scrollY};fn();addEventListener('scroll',fn,{passive:true});return()=>removeEventListener('scroll',fn)},[]);return <div className="site-shell designer-shell"><a className="skip-link" href="#main">Skip to content</a><PageMeta/><InteractionRuntime/><CursorFollower/><SlashTransition path={l.pathname}/><header className={`masthead${compact?' is-compact':''}`}><NavLink className="wordmark" to="/">NOQERI<span>/</span></NavLink><nav aria-label="Primary">{nav.map(([x,p])=><NavLink key={p} to={p}>{x}</NavLink>)}</nav><div className="header-actions"><span className="version-chip">Noqeri {clientVersion()}</span><a className="github-button" href="https://github.com/EMN90909/Noqeri" target="_blank" rel="noreferrer" aria-label="Noqeri on GitHub"><GithubIcon/></a><NavLink className="install-button" to="/install">Install</NavLink></div></header><main id="main" className="route-stage"><AnimatePresence mode="wait"><motion.div key={l.pathname} className="page-transition premium-route" initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:-4}} transition={{duration:reduced?0:tokens.duration.fast,ease:tokens.ease.editorial}}><Routes location={l}><Route path="/" element={<Home/>}/><Route path="/language" element={<Language/>}/><Route path="/docs/*" element={<Docs/>}/><Route path="/packages" element={<Packages/>}/><Route path="/registry" element={<Registry/>}/><Route path="/ecosystem" element={<Ecosystem/>}/><Route path="/benchmarks" element={<Benchmarks/>}/><Route path="/install" element={<Install/>}/><Route path="/playground" element={<Playground/>}/><Route path="/community" element={<Community/>}/><Route path="/about" element={<About/>}/><Route path="*" element={<NotFound/>}/></Routes></motion.div></AnimatePresence></main><footer><div className="footer-mark">NQ</div><div><strong>Noqeri 1.0</strong><br/>Compact, explicit, inspectable.</div><div className="footer-links"><NavLink to="/docs">Docs</NavLink><NavLink to="/packages">Packages</NavLink><NavLink to="/community">Community</NavLink><NavLink to="/about">About</NavLink></div><div className="made-by">Made by <strong>Noethric</strong></div></footer></div>}
